version: '3.8'
services:
  postgres-management:
    container_name: postgres-management
    image: postgres
    environment:
      POSTGRES_USER: dbmanagement
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: management
      PGDATA: /data/postgres
    volumes:
      - postgres-management:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres-management:
